version: "3"
services:
  app:
    image: chrisng93/hypeset-frontend
    depends_on:
      - server
    volumes:
      - .:/hypeset-frontend/
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  server:
    image: chrisng93/hypeset-backend
    volumes:
      - .:/hypeset-backend/
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hypeset
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/var/lib/redisql/data
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
