module.exports = {
  // auth
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAILURE: 'AUTH_FAILURE',
  // signUp
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  // editUser
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
  // getAllBrands
  GET_ALL_BRANDS_SUCCESS: 'GET_ALL_BRANDS_SUCCESS',
  GET_ALL_BRANDS_FAILURE: 'GET_ALL_BRANDS_FAILURE',
  // getUserBrands
  GET_USER_BRANDS_SUCCESS: 'GET_USER_BRANDS_SUCCESS',
  GET_USER_BRANDS_FAILURE: 'GET_USER_BRANDS_FAILURE',
  // addBrand
  ADD_BRAND_SUCCESS: 'ADD_BRAND_SUCCESS',
  ADD_BRAND_FAILURE: 'ADD_BRAND_FAILURE',
  // removeBrand
  REMOVE_BRAND_SUCCESS: 'REMOVE_BRAND_SUCCESS',
  REMOVE_BRAND_FAILURE: 'REMOVE_BRAND_FAILURE',
};
